import React, { useState, useEffect } from 'react';
import { api } from '../services/api';
import Loader from '../components/Loader';
import { Cpu, CpuIcon, Sparkles, TrendingUp, ShieldCheck, Flame, Moon, ArrowUpRight } from 'lucide-react';
import { 
  ResponsiveContainer, 
  LineChart, 
  Line, 
  XAxis, 
  YAxis, 
  Tooltip, 
  CartesianGrid, 
  Legend 
} from 'recharts';

export default function AIInsights() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAIAnalytics = async () => {
      try {
        const stats = await api.getAIAnalytics();
        setData(stats);
      } catch (err) {
        console.error("AI Insight compile error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchAIAnalytics();
  }, []);

  if (loading) {
    return <Loader text="Compiling machine learning predictions..." />;
  }

  const { forecastData, recommendations, anomalies } = data || {
    forecastData: [],
    recommendations: [],
    anomalies: []
  };

  return (
    <div className="space-y-6 md:space-y-8">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl md:text-2xl font-black text-slate-100 uppercase tracking-tight font-sans">
            AI Analytics & Forecasts
          </h2>
          <p className="text-xs text-slate-500 font-semibold uppercase tracking-wider">
            Predictive ML models, peak load predictions, and smart HVAC recommendations
          </p>
        </div>

        <div className="px-3.5 py-2 bg-slate-900 border border-slate-800 rounded-xl flex items-center gap-2 text-[10px] font-bold text-cyan-400 uppercase tracking-wider animate-pulse">
          <Sparkles size={14} className="text-cyan-400" />
          ML Engine Running
        </div>
      </div>

      {/* Actual vs Predicted Load Chart */}
      <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-4">
        <div className="flex justify-between items-start">
          <div>
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider flex items-center gap-2">
              <TrendingUp size={16} className="text-cyan-400" />
              Peak Load Prediction Model
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">LSTM regression actual vs predicted load (kW)</p>
          </div>
          <span className="text-[10px] text-emerald-400 font-bold uppercase tracking-wider px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/20 rounded-md">
            Accuracy: 98.4%
          </span>
        </div>

        <div className="h-72 md:h-80 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={forecastData} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
              <XAxis dataKey="day" stroke="#64748b" fontSize={10} tickLine={false} axisLine={false} />
              <YAxis stroke="#64748b" fontSize={10} tickLine={false} axisLine={false} />
              <Tooltip 
                contentStyle={{ backgroundColor: 'rgba(15, 23, 42, 0.95)', borderColor: 'rgba(255,255,255,0.08)' }} 
                itemStyle={{ color: '#f1f5f9', fontSize: '12px' }}
                labelStyle={{ color: '#94a3b8', fontSize: '10px', fontWeight: 'bold' }}
              />
              <Legend wrapperStyle={{ fontSize: '11px', fontWeight: 600, color: '#94a3b8' }} />
              <Line type="monotone" dataKey="actual" name="Actual Load" stroke="#1677ff" strokeWidth={2.5} activeDot={{ r: 6 }} dot={{ fill: '#1677ff' }} />
              <Line type="monotone" dataKey="predicted" name="AI Forecasted Load" stroke="#8b5cf6" strokeWidth={2} strokeDasharray="5 5" dot={{ fill: '#8b5cf6' }} />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Recommendations and ML Schedules */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* ML Recommendations list */}
        <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-6 lg:col-span-2">
          <div>
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider flex items-center gap-2">
              <Cpu size={16} className="text-cyan-400" />
              BEMS Action Optimization
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">Automated directives generated by neural network scanners</p>
          </div>

          <div className="space-y-4">
            {recommendations.map(rec => (
              <div 
                key={rec.id}
                className="bg-slate-950/40 border border-slate-800 hover:border-slate-700/60 rounded-2xl p-4 flex items-center justify-between gap-4 transition-colors"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2.5">
                    <span className={`px-2 py-0.5 rounded text-[9px] font-extrabold uppercase ${
                      rec.priority === 'High' ? 'bg-rose-500/10 text-rose-400' : 'bg-amber-500/10 text-amber-400'
                    }`}>
                      {rec.priority} Priority
                    </span>
                    <span className="text-[10px] text-slate-500 font-bold uppercase">{rec.type} Optimization</span>
                  </div>
                  <p className="text-xs text-slate-300 font-medium leading-relaxed mt-1.5">{rec.message}</p>
                </div>

                <div className="text-right shrink-0">
                  <span className="text-xs font-black text-emerald-400 block">+{rec.savings}</span>
                  <span className="text-[9px] font-bold text-slate-500 uppercase block tracking-wider mt-0.5">Est. Savings</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* HVAC Optimization Schedule */}
        <div className="bg-slate-900/40 border border-slate-800 rounded-3xl p-6 shadow-xl space-y-6">
          <div>
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider">AI HVAC Precooling</h3>
            <p className="text-xs text-slate-500 mt-0.5">Active cooling cycles preloaded into scheduler</p>
          </div>

          <div className="space-y-4">
            <div className="p-4 bg-slate-950/40 border border-slate-800/80 rounded-2xl flex items-center gap-3">
              <div className="p-2.5 bg-blue-500/10 text-blue-400 rounded-xl">
                <Moon size={16} />
              </div>
              <div>
                <span className="text-[9px] text-slate-500 font-bold uppercase tracking-wider block">Night pre-cooling</span>
                <span className="text-xs font-bold text-slate-200 block mt-0.5">OT HVAC set to 17°C (02:00 - 05:00)</span>
              </div>
            </div>

            <div className="p-4 bg-slate-950/40 border border-slate-800/80 rounded-2xl flex items-center gap-3">
              <div className="p-2.5 bg-rose-500/10 text-rose-400 rounded-xl">
                <Flame size={16} />
              </div>
              <div>
                <span className="text-[9px] text-slate-500 font-bold uppercase tracking-wider block">Peak load preemptive cycle</span>
                <span className="text-xs font-bold text-slate-200 block mt-0.5">Wards HVAC set to 23°C (12:00 - 15:00)</span>
              </div>
            </div>

            <div className="p-4 bg-slate-950/40 border border-slate-800/80 rounded-2xl flex items-center gap-3">
              <div className="p-2.5 bg-emerald-500/10 text-emerald-400 rounded-xl">
                <ShieldCheck size={16} />
              </div>
              <div>
                <span className="text-[9px] text-slate-500 font-bold uppercase tracking-wider block">Air quality purge cycle</span>
                <span className="text-xs font-bold text-slate-200 block mt-0.5">ICU air cycle increased (+15%) at 10:00</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
